run:
    run_type: "batch"

story_pipeline:
    gpu: 0

generation_args:
    seed: 40
    n_steps: 50
    same_latent: False
    share_queries: True
    perform_sdsa: True
    perform_injection: True
    n_anchors: 2

save_images:
    out_dir: output
    downscale_rate: 4
    save_image_all: True

prompts:
    style: "An illustration of "
    subject: "a white fish"
    concept_token: "fish"
    settings: [ "on an oval plate", "in a crown", "on the counter"]




